// Code generated by cmd/genregen from src/genre.tsv; DO NOT EDIT.

package main

func genreNameByID(id int) (string, bool) {
	switch id {
	case 1:
		return "Фантастика", true
	case 2:
		return "Проза", true
	case 3:
		return "Наука, Образование", true
	case 4:
		return "Детективы и Триллеры", true
	case 5:
		return "Документальная литература", true
	case 6:
		return "Любовные романы", true
	case 7:
		return "Детское", true
	case 8:
		return "Домоводство", true
	case 9:
		return "Религия и духовность", true
	case 10:
		return "Приключения", true
	case 11:
		return "Прочее", true
	case 12:
		return "Юмор", true
	case 13:
		return "Поэзия", true
	case 14:
		return "Справочная литература", true
	case 15:
		return "Техника", true
	case 16:
		return "Военное дело", true
	case 17:
		return "Компьютеры и Интернет", true
	case 18:
		return "Драматургия", true
	case 19:
		return "Старинное", true
	case 20:
		return "Деловая литература", true
	case 21:
		return "Фольклор", true
	case 22:
		return "Культура и искусство", true
	case 100:
		return "Научная фантастика", true
	case 101:
		return "Фэнтези", true
	case 102:
		return "Боевая фантастика", true
	case 103:
		return "Ужасы", true
	case 104:
		return "Юмористическая фантастика", true
	case 105:
		return "Альтернативная история", true
	case 106:
		return "Социальная фантастика", true
	case 107:
		return "Космическая фантастика", true
	case 108:
		return "Любовная фантастика", true
	case 109:
		return "Детская фантастика", true
	case 110:
		return "Героическая фантастика", true
	case 111:
		return "Детективная фантастика", true
	case 112:
		return "Эпическая фантастика", true
	case 113:
		return "Городское фэнтези", true
	case 114:
		return "Постапокалипсис", true
	case 115:
		return "Мистика", true
	case 116:
		return "Киберпанк", true
	case 117:
		return "Попаданцы", true
	case 118:
		return "Фантастика: прочее", true
	case 120:
		return "Сказочная фантастика", true
	case 121:
		return "Ненаучная фантастика", true
	case 122:
		return "Ироническое фэнтези", true
	case 123:
		return "Готический роман", true
	case 124:
		return "Ироническая фантастика", true
	case 125:
		return "Историческое фэнтези", true
	case 126:
		return "Стимпанк", true
	case 127:
		return "Технофэнтези", true
	case 128:
		return "Юмористическое фэнтези", true
	case 129:
		return "Хроноопера", true
	case 130:
		return "ЛитРПГ", true
	case 131:
		return "Альтернативная история", true
	case 132:
		return "Славянское фэнтези", true
	case 200:
		return "Современная проза", true
	case 201:
		return "Классическая проза", true
	case 202:
		return "Русская классическая проза", true
	case 203:
		return "Советская классическая проза", true
	case 204:
		return "Историческая проза", true
	case 205:
		return "О войне", true
	case 206:
		return "Рассказ", true
	case 207:
		return "Проза", true
	case 208:
		return "Контркультура", true
	case 209:
		return "Эпистолярная проза", true
	case 210:
		return "Роман", true
	case 211:
		return "Эссе, очерк, этюд, набросок", true
	case 212:
		return "Повесть", true
	case 213:
		return "Антисоветская литература", true
	case 214:
		return "Магический реализм", true
	case 215:
		return "Афоризмы", true
	case 216:
		return "Новелла", true
	case 217:
		return "Семейный роман/Семейная сага", true
	case 218:
		return "Сентиментальная проза", true
	case 219:
		return "Эпопея", true
	case 220:
		return "Феерия", true
	case 221:
		return "Классическая проза ХX века", true
	case 222:
		return "Классическая проза ХIX века", true
	case 223:
		return "Классическая проза XVII-XVIII веков", true
	case 224:
		return "Экспериментальная, неформатная проза", true
	case 225:
		return "Классическая русская поэзия", true
	case 226:
		return "Зарубежная классическая проза", true
	case 227:
		return "Фантасмагория, абсурдистская проза", true
	case 300:
		return "История", true
	case 301:
		return "Психология", true
	case 302:
		return "Философия", true
	case 303:
		return "Технические науки", true
	case 304:
		return "Политика", true
	case 305:
		return "Научная литература: прочее", true
	case 306:
		return "Культурология", true
	case 307:
		return "Литературоведение", true
	case 308:
		return "Языкознание", true
	case 309:
		return "Медицина", true
	case 310:
		return "Юриспруденция", true
	case 311:
		return "Учебники", true
	case 312:
		return "Религиоведение", true
	case 313:
		return "Биология", true
	case 314:
		return "Военная история", true
	case 315:
		return "Математика", true
	case 316:
		return "Физика", true
	case 317:
		return "Деловая литература", true
	case 318:
		return "Педагогика", true
	case 319:
		return "Астрономия и Космос", true
	case 320:
		return "Экономика", true
	case 321:
		return "Шпаргалки", true
	case 322:
		return "Альтернативная медицина", true
	case 323:
		return "Геология и география", true
	case 324:
		return "Химия", true
	case 325:
		return "Обществознание", true
	case 326:
		return "Государство и право", true
	case 327:
		return "Зоология", true
	case 328:
		return "Ботаника", true
	case 329:
		return "Экология", true
	case 330:
		return "Иностранные языки", true
	case 331:
		return "Биохимия", true
	case 332:
		return "Детская психология", true
	case 333:
		return "Ветеринария", true
	case 334:
		return "Физическая химия", true
	case 335:
		return "Секс и семейная психология", true
	case 336:
		return "Психотерапия и консультирование", true
	case 337:
		return "Биофизика", true
	case 338:
		return "Органическая химия", true
	case 339:
		return "Аналитическая химия", true
	case 340:
		return "Рефераты", true
	case 341:
		return "Учебники и пособия ВУЗов", true
	case 342:
		return "Учебники и пособия для среднего и специального образования", true
	case 343:
		return "Школьные учебники и пособия, рефераты, шпаргалки", true
	case 344:
		return "Востоковедение", true
	case 400:
		return "Детективы: прочее", true
	case 401:
		return "Триллер", true
	case 402:
		return "Классический детектив", true
	case 403:
		return "Боевик", true
	case 404:
		return "Полицейский детектив", true
	case 405:
		return "Детские остросюжетные", true
	case 406:
		return "Любовные детективы", true
	case 407:
		return "Криминальный детектив", true
	case 408:
		return "Исторический детектив", true
	case 409:
		return "Иронический детектив", true
	case 410:
		return "Шпионский детектив", true
	case 411:
		return "Крутой детектив", true
	case 412:
		return "Дамский детективный роман", true
	case 414:
		return "Политический детектив", true
	case 415:
		return "Маньяки", true
	case 416:
		return "Юридический триллер", true
	case 417:
		return "Медицинский триллер", true
	case 418:
		return "Техно триллер", true
	case 419:
		return "Советский детектив", true
	case 420:
		return "Психологический триллер", true
	case 500:
		return "Биографии и Мемуары", true
	case 501:
		return "Публицистика", true
	case 502:
		return "Путешествия и география", true
	case 503:
		return "Научпоп", true
	case 504:
		return "Документальная литература", true
	case 505:
		return "Природа и животные", true
	case 506:
		return "Критика", true
	case 507:
		return "Военная документалистика", true
	case 508:
		return "География, путевые заметки", true
	case 600:
		return "Короткие любовные романы", true
	case 601:
		return "Современные любовные романы", true
	case 602:
		return "Исторические любовные романы", true
	case 604:
		return "О любви", true
	case 607:
		return "Эротика", true
	case 608:
		return "Порно", true
	case 700:
		return "Детская литература: прочее", true
	case 701:
		return "Сказка", true
	case 702:
		return "Детская проза", true
	case 705:
		return "Образовательная литература", true
	case 706:
		return "Детские стихи", true
	case 707:
		return "Детские приключения", true
	case 708:
		return "Книга-игра", true
	case 709:
		return "Подростковая литература", true
	case 710:
		return "Детский фольклор", true
	case 711:
		return "Русские сказки", true
	case 712:
		return "Классическая детская литература", true
	case 713:
		return "Зарубежная детская литература", true
	case 714:
		return "Детские детективы", true
	case 800:
		return "Эротика, Секс", true
	case 801:
		return "Кулинария", true
	case 802:
		return "Здоровье", true
	case 803:
		return "Хобби и ремесла", true
	case 804:
		return "Спорт", true
	case 805:
		return "Домашние животные", true
	case 806:
		return "Домоводство", true
	case 807:
		return "Сделай сам", true
	case 808:
		return "Сад и огород", true
	case 809:
		return "Развлечения", true
	case 810:
		return "Коллекционирование", true
	case 811:
		return "Семейные отношения", true
	case 900:
		return "Эзотерика", true
	case 901:
		return "Религия", true
	case 902:
		return "Христианство", true
	case 903:
		return "Православие", true
	case 904:
		return "Самосовершенствование", true
	case 905:
		return "Буддизм", true
	case 906:
		return "Иудаизм", true
	case 907:
		return "Астрология", true
	case 908:
		return "Протестантизм", true
	case 909:
		return "Индуизм", true
	case 910:
		return "Католицизм", true
	case 911:
		return "Язычество", true
	case 912:
		return "Ислам", true
	case 913:
		return "Хиромантия", true
	case 914:
		return "Религиозная литература: прочее", true
	case 1000:
		return "Приключения: прочее", true
	case 1001:
		return "Исторические приключения", true
	case 1005:
		return "Морские приключения", true
	case 1006:
		return "Вестерн", true
	case 1007:
		return "Приключения про индейцев", true
	case 1009:
		return "Авантюрный роман", true
	case 1010:
		return "Приключения в современном мире", true
	case 1011:
		return "Рыцарский роман", true
	case 1012:
		return "Приключения для детей и подростков", true
	case 1013:
		return "Природа и животные", true
	case 1014:
		return "Путешествия и география", true
	case 1100:
		return "Газеты и журналы", true
	case 1101:
		return "Недописанное", true
	case 1102:
		return "Фанфик", true
	case 1104:
		return "Кино", true
	case 1105:
		return "Партитуры", true
	case 1108:
		return "Сетевая литература", true
	case 1109:
		return "Альтернативные науки и научные теории", true
	case 1110:
		return "Диафильмы", true
	case 1111:
		return "Комиксы", true
	case 1112:
		return "Неотсортированное", true
	case 1113:
		return "Машинный перевод", true
	case 1114:
		return "Любительский перевод", true
	case 1201:
		return "Юмористическая проза", true
	case 1202:
		return "Юмор: прочее", true
	case 1203:
		return "Комедия", true
	case 1204:
		return "Анекдоты", true
	case 1205:
		return "Юмористические стихи", true
	case 1206:
		return "Сатира", true
	case 1300:
		return "Поэзия: прочее", true
	case 1303:
		return "Лирика", true
	case 1304:
		return "в стихах", true
	case 1305:
		return "Эпическая поэзия", true
	case 1306:
		return "Басни", true
	case 1307:
		return "Песенная поэзия", true
	case 1308:
		return "Палиндромы", true
	case 1309:
		return "Экспериментальная поэзия", true
	case 1310:
		return "Верлибры", true
	case 1311:
		return "Визуальная поэзия", true
	case 1312:
		return "Поэзия Востока", true
	case 1313:
		return "Современная поэзия", true
	case 1314:
		return "Современная русская поэзия", true
	case 1315:
		return "Современная зарубежная поэзия", true
	case 1316:
		return "Поэма, эпическая поэзия", true
	case 1318:
		return "Классическая поэзия", true
	case 1319:
		return "Классическая зарубежная поэзия", true
	case 1400:
		return "Энциклопедии", true
	case 1401:
		return "Справочники", true
	case 1402:
		return "Руководства", true
	case 1403:
		return "Искусство и Дизайн", true
	case 1404:
		return "Справочная литература", true
	case 1405:
		return "Словари", true
	case 1406:
		return "Путеводители", true
	case 1501:
		return "Радиоэлектроника", true
	case 1502:
		return "Транспорт и авиация", true
	case 1503:
		return "Строительство и сопромат", true
	case 1504:
		return "Автомобили и ПДД", true
	case 1505:
		return "Архитектура", true
	case 1506:
		return "Металлургия", true
	case 1507:
		return "История техники", true
	case 1508:
		return "Автодело", true
	case 1602:
		return "Военная техника и вооружение", true
	case 1604:
		return "Боевые искусства", true
	case 1605:
		return "Cпецслужбы", true
	case 1606:
		return "Военное дело: прочее", true
	case 1700:
		return "Околокомпьютерная литература", true
	case 1701:
		return "Программирование", true
	case 1702:
		return "ОС и Сети", true
	case 1703:
		return "Программы", true
	case 1704:
		return "Аппаратное обеспечение", true
	case 1705:
		return "Интернет", true
	case 1706:
		return "Базы данных", true
	case 1707:
		return "Цифровая обработка сигналов", true
	case 1708:
		return "Учебные пособия, самоучители", true
	case 1800:
		return "Драматургия: прочее", true
	case 1802:
		return "Драма", true
	case 1803:
		return "Трагедия", true
	case 1804:
		return "Киносценарии", true
	case 1805:
		return "Сценарии", true
	case 1806:
		return "Водевиль", true
	case 1807:
		return "Мистерия", true
	case 1808:
		return "Античная драма", true
	case 1900:
		return "Мифы. Легенды. Эпос", true
	case 1901:
		return "Античная литература", true
	case 1902:
		return "Древневосточная литература", true
	case 1903:
		return "Древнеевропейская литература", true
	case 1904:
		return "Старинная литература: прочее", true
	case 1905:
		return "Древнерусская литература", true
	case 1906:
		return "Средневековая классическая проза", true
	case 1907:
		return "Античная драма", true
	case 2000:
		return "О бизнесе популярно", true
	case 2001:
		return "Маркетинг, PR, реклама", true
	case 2002:
		return "Управление, подбор персонала", true
	case 2003:
		return "Экономика", true
	case 2004:
		return "Ценные бумаги, инвестиции", true
	case 2005:
		return "Бухучет и аудит", true
	case 2006:
		return "Личные финансы", true
	case 2007:
		return "Поиск работы, карьера", true
	case 2008:
		return "Малый бизнес", true
	case 2009:
		return "Корпоративная культура", true
	case 2010:
		return "Банковское дело", true
	case 2011:
		return "Делопроизводство", true
	case 2012:
		return "Отраслевые издания", true
	case 2013:
		return "Недвижимость", true
	case 2014:
		return "Внешняя торговля", true
	case 2015:
		return "Торговля", true
	case 2016:
		return "Деловая литература", true
	case 2100:
		return "Народные сказки", true
	case 2102:
		return "Фольклор: прочее", true
	case 2104:
		return "Былины", true
	case 2105:
		return "Пословицы, поговорки", true
	case 2106:
		return "Народные песни", true
	case 2107:
		return "Частушки, прибаутки, потешки", true
	case 2108:
		return "Загадки", true
	case 2109:
		return "Современная сказка", true
	case 2200:
		return "Искусствоведение", true
	case 2201:
		return "Живопись, альбомы, иллюстрированные каталоги", true
	case 2202:
		return "Мировая художественная культура", true
	case 2203:
		return "Изобразительное искусство, фотография", true
	case 2204:
		return "Театр", true
	case 2205:
		return "Музыка", true
	case 2206:
		return "Культура и искусство: прочее", true
	default:
		return "", false
	}
}
