// Genregen reads freeLib src/genre.tsv and writes flib/genres_generated.go (map id -> name).
//
//	go run ./cmd/genregen -in ../src/genre.tsv -out genres_generated.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	inPath := flag.String("in", filepath.Join("..", "src", "genre.tsv"), "path to genre.tsv")
	outPath := flag.String("out", "genres_generated.go", "output Go file path (relative to cwd)")
	flag.Parse()

	data, err := os.ReadFile(*inPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genregen: read %s: %v\n", *inPath, err)
		os.Exit(1)
	}
	ids, names, err := parseGenreTSV(string(data))
	if err != nil {
		fmt.Fprintf(os.Stderr, "genregen: %v\n", err)
		os.Exit(1)
	}
	if err := writeGenerated(*outPath, ids, names); err != nil {
		fmt.Fprintf(os.Stderr, "genregen: %v\n", err)
		os.Exit(1)
	}
}

func parseGenreTSV(content string) ([]int, []string, error) {
	type pair struct {
		id   int
		name string
	}
	var pairs []pair
	sc := bufio.NewScanner(strings.NewReader(content))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.Split(line, "\t")
		if len(parts) < 3 {
			continue
		}
		id, err := strconv.Atoi(strings.TrimSpace(parts[1]))
		if err != nil {
			continue
		}
		name := strings.TrimSpace(parts[2])
		pairs = append(pairs, pair{id: id, name: name})
	}
	if err := sc.Err(); err != nil {
		return nil, nil, err
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].id < pairs[j].id })
	ids := make([]int, len(pairs))
	names := make([]string, len(pairs))
	for i := range pairs {
		ids[i] = pairs[i].id
		names[i] = pairs[i].name
	}
	return ids, names, nil
}

func writeGenerated(outPath string, ids []int, names []string) error {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by cmd/genregen from src/genre.tsv; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package main\n\n")
	fmt.Fprintf(&b, "func genreNameByID(id int) (string, bool) {\n")
	fmt.Fprintf(&b, "\tswitch id {\n")
	for i := range ids {
		fmt.Fprintf(&b, "\tcase %d:\n\t\treturn %s, true\n", ids[i], strconv.Quote(names[i]))
	}
	fmt.Fprintf(&b, "\tdefault:\n\t\treturn \"\", false\n")
	fmt.Fprintf(&b, "\t}\n}\n")
	return os.WriteFile(outPath, []byte(b.String()), 0o644)
}
